/* Crystalina sales portal, browser-backed prototype. */
(() => {
  const ROLE = 'Sales Associate'; let pendingEmail = ''; let stageFilter = '';
  const auth = document.getElementById('salesAuth'); const shell = document.getElementById('salesShell'); const error = document.getElementById('salesError');
  const showError = message => { error.textContent = message; error.classList.toggle('show', Boolean(message)); };
  function showPortal(session) { auth.hidden = true; shell.hidden = false; document.getElementById('salesName').textContent = session.name; document.getElementById('salesId').textContent = session.id; render(); window.dispatchEvent(new CustomEvent('staff-session-ready')); }
  document.getElementById('salesEmailForm').addEventListener('submit', event => { event.preventDefault(); pendingEmail = document.getElementById('salesEmail').value.trim(); const result = Store.requestStaffCode(pendingEmail, ROLE); if (!result.ok) return showError(result.error); showError(''); event.currentTarget.hidden = true; document.getElementById('salesCodeForm').hidden = false; const note = document.getElementById('salesPrototype'); note.hidden = false; note.innerHTML = `<strong>Prototype verification</strong><span>Email delivery will be connected with the backend. Use demo code <b>${result.demoCode}</b>.</span>`; });
  document.getElementById('salesCodeForm').addEventListener('submit', event => { event.preventDefault(); const result = Store.verifyStaffCode(pendingEmail, document.getElementById('salesCode').value.trim(), ROLE); if (!result.ok) return showError(result.error); showPortal(result.staff); });
  document.getElementById('salesSignOut').addEventListener('click', () => { Store.staffSignOut(); location.reload(); });
  document.getElementById('salesLeadFilter').addEventListener('input', event => { stageFilter = event.target.value; render(); });
  function render() { const data = Store.getAdminData(); const leads = data.leads.filter(lead => !stageFilter || lead.stage === stageFilter); const open = data.leads.filter(lead => !['Won','Lost'].includes(lead.stage)); const owned = data.customers.filter(customer => customer.assignedSalesId === Store.currentStaff().id); document.getElementById('salesStats').innerHTML = `<div class="stat-card"><div class="sc-label">Open Leads</div><div class="sc-value">${open.length}</div><div class="sc-hint">${money(open.reduce((sum,lead)=>sum+Number(lead.value),0))} pipeline</div></div><div class="stat-card"><div class="sc-label">Customers</div><div class="sc-value">${owned.length}</div><div class="sc-hint">linked to ${escapeHTML(Store.currentStaff().id)}</div></div><div class="stat-card"><div class="sc-label">Won</div><div class="sc-value">${data.leads.filter(lead=>lead.stage==='Won').length}</div><div class="sc-hint">converted leads</div></div><div class="stat-card"><div class="sc-label">Cart Recovery</div><div class="sc-value">${data.abandonedCarts.filter(cart=>cart.status==='Pending').length}</div><div class="sc-hint">pending contacts</div></div>`; document.querySelector('#salesLeads tbody').innerHTML = leads.map(lead => `<tr><td><strong>${escapeHTML(lead.name)}</strong><br><small>${escapeHTML(lead.email)}</small></td><td>${escapeHTML(lead.interest)}</td><td>${money(Number(lead.value))}</td><td>${new Date(lead.followUp+'T12:00:00').toLocaleDateString()}</td><td><select class="admin-select" onchange="SalesUI.stage('${lead.id}',this.value)">${['New','Qualified','Quote sent','Won','Lost'].map(status=>`<option ${status===lead.stage?'selected':''}>${status}</option>`).join('')}</select></td><td><button class="btn btn-sm btn-outline" onclick="SalesUI.convert('${lead.id}')" ${lead.stage==='Won'?'disabled':''}>Convert to Customer</button></td></tr>`).join(''); document.querySelector('#salesCampaigns tbody').innerHTML = data.campaigns.map(campaign => `<tr><td><strong>${escapeHTML(campaign.name)}</strong><br><small>${escapeHTML(campaign.channel)}</small></td><td>${escapeHTML(campaign.audience)}</td><td>${campaign.conversion}%</td><td><select class="admin-select" onchange="SalesUI.campaign('${campaign.id}',this.value)">${['Draft','Scheduled','Active','Paused','Completed'].map(status=>`<option ${status===campaign.status?'selected':''}>${status}</option>`).join('')}</select></td></tr>`).join(''); document.querySelector('#salesCarts tbody').innerHTML = data.abandonedCarts.map(cart => `<tr><td><strong>${escapeHTML(cart.customer)}</strong></td><td>${escapeHTML(cart.email)}<br><small>${escapeHTML(cart.phone||'No SMS')}</small></td><td>${cart.items.map(escapeHTML).join('<br>')}</td><td>${money(Number(cart.total))}</td><td>${escapeHTML(cart.status)}</td><td><button class="btn btn-sm btn-outline" onclick="SalesUI.recover('${cart.id}')">Queue Reminder</button></td></tr>`).join(''); }
  document.getElementById('salesLeadForm').addEventListener('submit', event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const id = 'LEAD-' + String(Date.now()).slice(-5); Store.addAdminItem('leads', { id, ...values, value: Number(values.value), source: `Sales Associate ${Store.currentStaff().id}`, stage: 'New', createdBy: Store.currentStaff().id }); Store.logActivity(Store.currentStaff().id, 'Created sales lead', id); event.currentTarget.reset(); render(); toast('Lead created'); });
  document.getElementById('salesCustomerForm').addEventListener('submit', event => { event.preventDefault(); const values = Object.fromEntries(new FormData(event.currentTarget).entries()); const id = 'CUS-' + String(Date.now()).slice(-5); Store.addAdminItem('customers', { id, name: values.name, email: values.email, phone: values.phone, joined: new Date().toISOString().slice(0,10), address: values.address, source: 'Sales Associate', assignedSalesId: Store.currentStaff().id, products: [values.product], cart: [], installed: [], notes: `Created by ${Store.currentStaff().id}.` }); Store.logActivity(Store.currentStaff().id, 'Created customer and recorded sale', id); event.currentTarget.reset(); render(); toast('Customer and sale recorded'); });
  window.SalesUI = { stage(id, stage) { Store.updateAdminItem('leads', id, { stage, updatedBy: Store.currentStaff().id }); Store.logActivity(Store.currentStaff().id, `Changed lead stage to ${stage}`, id); render(); }, convert(id) { const lead = Store.getAdminData().leads.find(item=>item.id===id); if(!lead)return; const customerId='CUS-'+String(Date.now()).slice(-5); Store.addAdminItem('customers',{id:customerId,name:lead.name,email:lead.email,phone:'Not provided',joined:new Date().toISOString().slice(0,10),address:`${lead.borough}, NY`,source:'Sales Associate',assignedSalesId:Store.currentStaff().id,products:[lead.interest],cart:[],installed:[],notes:`Converted from ${lead.id} by ${Store.currentStaff().id}.`}); Store.updateAdminItem('leads',id,{stage:'Won',convertedCustomerId:customerId,updatedBy:Store.currentStaff().id}); Store.logActivity(Store.currentStaff().id,'Converted lead and created customer',customerId); render(); toast('Lead converted to customer'); }, campaign(id,status){Store.updateAdminItem('campaigns',id,{status,updatedBy:Store.currentStaff().id});Store.logActivity(Store.currentStaff().id,`Changed campaign status to ${status}`,id);render();}, recover(id){const cart=Store.getAdminData().abandonedCarts.find(item=>item.id===id);if(!cart)return;Store.addAdminItem('outreach',{id:'OUT-'+String(Date.now()).slice(-6),audience:`cart:${id}`,channel:'Email + SMS',subject:'Complete your Crystalina order',message:'Your selected filtration products are still waiting in your cart.',recipients:[cart.email],count:1,created:new Date().toISOString(),status:'Queued',createdBy:Store.currentStaff().id});Store.updateAdminItem('abandonedCarts',id,{status:'Contacted'});Store.logActivity(Store.currentStaff().id,'Queued abandoned-cart recovery',id);render();toast('Cart recovery reminder queued');} };
  const session = Store.currentStaff(); const liveMember = session && Store.getAdminData().staff.find(member => member.id === session.id); if (liveMember && (liveMember.roles || [liveMember.role]).includes(ROLE) && session.activeRole === ROLE) showPortal(session);
})();
